In [1]:
import torch

In [11]:
# matrix
t1 = torch.tensor([1.0,2,3,4,5,6,7])
print(t1.shape, t1.dtype)

torch.Size([7]) torch.float32


In [12]:
# matrix
t2 = torch.tensor([[0,1],[2,3],[4,5],[6,7]])
print(t2.shape, t2.dtype)

torch.Size([4, 2]) torch.int64


### Operations and gradients 

In [18]:
x = torch.tensor(3.)
w = torch.tensor(4., requires_grad=True)
b = torch.tensor(5., requires_grad=True)

In [19]:
y = x*w + b
y

tensor(17., grad_fn=<AddBackward0>)

In [21]:
# Compute derivatives
y.backward()

In [23]:
# Display gradients
print('dy/dx', x.grad)
print('dy/dw', w.grad)
print('dy/db', b.grad)

dy/dx None
dy/dw tensor(3.)
dy/db tensor(1.)


### Interpropability with Numpy

In [24]:
import numpy as np

In [25]:
x = np.array([[1,2],[3,4.]])
x

array([[1., 2.],
       [3., 4.]])

In [26]:
# Convert to tensor
y = torch.from_numpy(x)
y

tensor([[1., 2.],
        [3., 4.]], dtype=torch.float64)

In [27]:
# And back to numpy
y.numpy()

array([[1., 2.],
       [3., 4.]])